development:
  adapter:  mysql
  database: mole_test
  username: root
  password:
  host:     localhost
  
production:
  adapter:  mysql
  database: mole_test
  username: root
  password:
  host:     localhost  